package exception.throw_;

public class ThrowEX01 {
	public static void main(String[] args) {
		/*
		 * 예외 생성하기 (throw new)
		 * - 메서드 실행도중에 throw 키워를 만나면 즉시 throw로 생성한 예외가 발생된다.
		 * - 예외가 발생되면 실행된 코드는 즉시 중단되고, 예외를 처리할 수 있는 catch문으로 이동합니다.
		 * - 
		 * 
		 */
		try {
			System.out.println("결과 : " + calc(10));
			System.out.println("결과 : " + calc(-10));
		} catch (Exception e) {
			System.out.println("반드시 양수값을 전달해야 합니다.");
		}

	} // main end

	public static int calc(int n) throws Exception {
		if (n < 0) {
			throw new Exception(); // 예외 생성
		}
		int sum = 0;
		for (int i = 1; i <= n; i++) {
			sum += i;
		}
		return sum;
	} // calc end

	
}
